### ISSUE TITLE
[Question] Can I use your the class animations for a personal project?

### ISSUE THREAD

**Issue by Aearsears** [ikasuu/grandislibrary-next#1]
Hello Ikasuu, not sure where I could ask you about this and couldn't get into the discord server because the link is broken. I want to ask if I could use the class skill animations for a personal non-commercial project? I will of course add credits.

**Comment by ikasuu** [comment]
Hey Aearsears, feel free to use the class skill animations.

If you're looking for more raw skill animations. Maple Editors has all of the skills up to Hoyoung (missing Adele, Kain, and Lara) frame by frame on transparent backgrounds.

https://mapleeditors.com/skills/
